# Generated by Django 4.2.7 on 2026-05-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for this course (e.g. https://youtube.com/watch?v=...)'),
        ),
    ]
