# Generated by Django 4.2.7 on 2026-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='book', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
